#开发环境配置
server:
  #服务端口
  port: 8089
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 200
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 25

#spring 环境配置
spring:
  thymeleaf: 
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths:  /** 
  #数据源
  datasource:
#    url: jdbc:oracle:thin:@172.16.13.5:1521/scnh
#    url: jdbc:oracle:thin:@GSMP
#    username: ptwg
#    password: ptwg#2019
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    ds1: #数据源1
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@172.26.168.104:1521/gsmp
      username: cmps # 用户名
      password: cmps#2017 # 密码
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    ds2: # 数据源2
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.58.3:1521/wgqzcjk
      username: PINGTAN_LS # 用户名
      password: PINGtan_ls##123 # 密码
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
#日志配置
logging:
  path: d:\\syncDatalogs
  level:
    net.evecom.service.impl: DEBUG
    org.springframework: INFO
    org.spring.springboot.dao: DEBUG

cron:
  cmps:
    pop: 33 18 09 * * ?
    localpop: 33 22 09 * * ?
    flowpop: 33 25 09 * * ?
    grugpop: 33 25 14 * * ?
#对接的clienId（正式）
#sycBaseUrl: http://newapi.fjsq.fj.cegn.cn
#clientid: 8820178908
#secretkey: tlw8wd1da9eypdrq3m070csp2pmeuqo3
#对接的clienId（测试）
sycBaseUrl: http://api.beta.aishequ.org
#clientid: 7404918535
#secretkey: s01yc5f6qe7dp7bujouv2d85nfj1r57m
clientid: 8820178908
secretkey: tlw8wd1da9eypdrq3m070csp2pmeuqo3
#事件对接登录用户名密码（正式）
#evtusername: nhadmin
#password: d0278017825373a7ea9a94b62d55e429
#事件对接登录用户名密码（测试）
evtusername: sanming
password: 8b8418fa89b5ff58b4503319cbed8827
#系统地址前缀（正式）
#cmpsDomain: http://172.24.3.57:8073/cmps
#cmpsDomain2: http://172.24.3.57:8072/scnh
downloadDomain: http://10.10.10.217:8072/scnh
#系统地址前缀（测试）
cmpsDomain: http://110.85.58.153:7010/cmps
cmpsDomain2: http://110.85.58.153:7020/emnh
#一次性对接多少
onceSyncRows: 100
#错误日志位置
errorDatalogs:  d:\\errorDatalogs
#网格文件地址
gridPath:
